// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    console.log("hogehoge");
    $(".row.fitHeight").each(function() {
      var h;
      h = $(".col-sm-6", this).height();
      return console.log(h);
    });
    return (function() {
      var w;
      w = $(".mkknHero .heroImg").width();
      return $(".mkknHero .heroImg").height(w / 2);
    })();
  });

}).call(this);
